/*
 * Copyright 2026 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package org.mifos.core.network.fineract.loans.dto

import kotlinx.serialization.Serializable

@Serializable
data class LoanDetailDto(
    val id: Long = 0,
    val accountNo: String? = null,
    val status: LoanDetailStatusDto? = null,
    val clientId: Long = 0,
    val clientAccountNo: String? = null,
    val clientName: String? = null,
    val clientOfficeId: Long = 0,
    val loanProductId: Long = 0,
    val loanProductName: String? = null,
    val loanProductDescription: String? = null,
    val isLoanProductLinkedToFloatingRate: Boolean = false,
    val loanType: LoanDetailTypeDto? = null,
    val currency: LoanDetailCurrencyDto? = null,
    val principal: Double = 0.0,
    val approvedPrincipal: Double = 0.0,
    val proposedPrincipal: Double = 0.0,
    val netDisbursalAmount: Double = 0.0,
    val termFrequency: Int = 0,
    val termPeriodFrequencyType: LoanDetailTypeDto? = null,
    val numberOfRepayments: Int = 0,
    val actualNoTerm: Int = 0,
    val repaymentEvery: Int = 0,
    val repaymentFrequencyType: LoanDetailTypeDto? = null,
    val interestRatePerPeriod: Double = 0.0,
    val interestRateFrequencyType: LoanDetailTypeDto? = null,
    val annualInterestRate: Double = 0.0,
    val isFloatingInterestRate: Boolean = false,
    val amortizationType: LoanDetailTypeDto? = null,
    val interestType: LoanDetailTypeDto? = null,
    val interestCalculationPeriodType: LoanDetailTypeDto? = null,
    val allowPartialPeriodInterestCalculation: Boolean = false,
    val transactionProcessingStrategyCode: String? = null,
    val transactionProcessingStrategyName: String? = null,
    val syncDisbursementWithMeeting: Boolean = false,
    val disallowExpectedDisbursements: Boolean = false,
    val timeline: LoanDetailTimelineDto? = null,
    val summary: LoanDetailSummaryDto? = null,
    val repaymentSchedule: LoanRepaymentScheduleDto? = null,
    val transactions: List<LoanTransactionDto> = emptyList(),
)

@Serializable
data class LoanDetailStatusDto(
    val id: Long = 0,
    val code: String? = null,
    val value: String? = null,
    val pendingApproval: Boolean = false,
    val waitingForDisbursal: Boolean = false,
    val active: Boolean = false,
    val closedObligationsMet: Boolean = false,
    val closedWrittenOff: Boolean = false,
    val closedRescheduled: Boolean = false,
    val closed: Boolean = false,
    val overpaid: Boolean = false,
)

@Serializable
data class LoanDetailTypeDto(
    val id: Long = 0,
    val code: String? = null,
    val value: String? = null,
)

@Serializable
data class LoanDetailCurrencyDto(
    val code: String? = null,
    val name: String? = null,
    val decimalPlaces: Int = 0,
    val inMultiplesOf: Int = 0,
    val displaySymbol: String? = null,
    val nameCode: String? = null,
    val displayLabel: String? = null,
)

@Serializable
data class LoanDetailTimelineDto(
    val submittedOnDate: List<Int>? = null,
    val submittedByUsername: String? = null,
    val submittedByFirstname: String? = null,
    val submittedByLastname: String? = null,
    val approvedOnDate: List<Int>? = null,
    val approvedByUsername: String? = null,
    val approvedByFirstname: String? = null,
    val approvedByLastname: String? = null,
    val expectedDisbursementDate: List<Int>? = null,
    val actualDisbursementDate: List<Int>? = null,
    val disbursedByUsername: String? = null,
    val disbursedByFirstname: String? = null,
    val disbursedByLastname: String? = null,
    val actualMaturityDate: List<Int>? = null,
    val expectedMaturityDate: List<Int>? = null,
)

@Serializable
data class LoanDetailSummaryDto(
    val currency: LoanDetailCurrencyDto? = null,
    val totalPrincipal: Double = 0.0,
    val totalCapitalizedIncome: Double = 0.0,
    val totalCapitalizedIncomeAdjustment: Double = 0.0,
    val principalDisbursed: Double = 0.0,
    val principalAdjustments: Double = 0.0,
    val principalPaid: Double = 0.0,
    val principalWrittenOff: Double = 0.0,
    val principalOutstanding: Double = 0.0,
    val principalOverdue: Double = 0.0,
    val interestCharged: Double = 0.0,
    val interestPaid: Double = 0.0,
    val interestWaived: Double = 0.0,
    val interestWrittenOff: Double = 0.0,
    val interestOutstanding: Double = 0.0,
    val interestOverdue: Double = 0.0,
    val feeChargesCharged: Double = 0.0,
    val feeAdjustments: Double = 0.0,
    val feeChargesDueAtDisbursementCharged: Double = 0.0,
    val feeChargesPaid: Double = 0.0,
    val feeChargesWaived: Double = 0.0,
    val feeChargesWrittenOff: Double = 0.0,
    val feeChargesOutstanding: Double = 0.0,
    val feeChargesOverdue: Double = 0.0,
    val penaltyChargesCharged: Double = 0.0,
    val penaltyAdjustments: Double = 0.0,
    val penaltyChargesPaid: Double = 0.0,
    val penaltyChargesWaived: Double = 0.0,
    val penaltyChargesWrittenOff: Double = 0.0,
    val penaltyChargesOutstanding: Double = 0.0,
    val penaltyChargesOverdue: Double = 0.0,
    val totalExpectedRepayment: Double = 0.0,
    val totalRepayment: Double = 0.0,
    val totalExpectedCostOfLoan: Double = 0.0,
    val totalCostOfLoan: Double = 0.0,
    val totalWaived: Double = 0.0,
    val totalWrittenOff: Double = 0.0,
    val totalOutstanding: Double = 0.0,
    val totalOverdue: Double = 0.0,
    val totalRecovered: Double = 0.0,
)

@Serializable
data class LoanRepaymentScheduleDto(
    val currency: LoanDetailCurrencyDto? = null,
    val loanTermInDays: Int = 0,
    val totalPrincipalDisbursed: Double = 0.0,
    val totalPrincipalExpected: Double = 0.0,
    val totalPrincipalPaid: Double = 0.0,
    val totalInterestCharged: Double = 0.0,
    val totalFeeChargesCharged: Double = 0.0,
    val totalPenaltyChargesCharged: Double = 0.0,
    val totalWaived: Double = 0.0,
    val totalWrittenOff: Double = 0.0,
    val totalRepaymentExpected: Double = 0.0,
    val totalRepayment: Double = 0.0,
    val totalPaidInAdvance: Double = 0.0,
    val totalPaidLate: Double = 0.0,
    val totalOutstanding: Double = 0.0,
    val totalCredits: Double = 0.0,
    val periods: List<LoanRepaymentPeriodDto> = emptyList(),
)

@Serializable
data class LoanRepaymentPeriodDto(
    val period: Int? = null,
    val fromDate: List<Int>? = null,
    val dueDate: List<Int>? = null,
    val complete: Boolean = false,
    val daysInPeriod: Int? = null,
    val principalOriginalDue: Double = 0.0,
    val principalDue: Double = 0.0,
    val principalPaid: Double = 0.0,
    val principalWrittenOff: Double = 0.0,
    val principalOutstanding: Double = 0.0,
    val principalLoanBalanceOutstanding: Double = 0.0,
    val interestOriginalDue: Double = 0.0,
    val interestDue: Double = 0.0,
    val interestPaid: Double = 0.0,
    val interestWaived: Double = 0.0,
    val interestWrittenOff: Double = 0.0,
    val interestOutstanding: Double = 0.0,
    val feeChargesDue: Double = 0.0,
    val feeChargesPaid: Double = 0.0,
    val feeChargesWaived: Double = 0.0,
    val feeChargesWrittenOff: Double = 0.0,
    val feeChargesOutstanding: Double = 0.0,
    val penaltyChargesDue: Double = 0.0,
    val penaltyChargesPaid: Double = 0.0,
    val penaltyChargesWaived: Double = 0.0,
    val penaltyChargesWrittenOff: Double = 0.0,
    val penaltyChargesOutstanding: Double = 0.0,
    val totalOriginalDueForPeriod: Double = 0.0,
    val totalDueForPeriod: Double = 0.0,
    val totalPaidForPeriod: Double = 0.0,
    val totalPaidInAdvanceForPeriod: Double = 0.0,
    val totalPaidLateForPeriod: Double = 0.0,
    val totalWaivedForPeriod: Double = 0.0,
    val totalWrittenOffForPeriod: Double = 0.0,
    val totalOutstandingForPeriod: Double = 0.0,
    val totalActualCostOfLoanForPeriod: Double = 0.0,
    val totalInstallmentAmountForPeriod: Double = 0.0,
    val totalCredits: Double = 0.0,
    val totalAccruedInterest: Double = 0.0,
    val downPaymentPeriod: Boolean = false,
)

@Serializable
data class LoanTransactionDto(
    val id: Long = 0,
    val loanId: Long = 0,
    val officeId: Long = 0,
    val officeName: String? = null,
    val type: LoanTransactionTypeDto? = null,
    val date: List<Int>? = null,
    val currency: LoanDetailCurrencyDto? = null,
    val amount: Double = 0.0,
    val netDisbursalAmount: Double = 0.0,
    val principalPortion: Double = 0.0,
    val interestPortion: Double = 0.0,
    val feeChargesPortion: Double = 0.0,
    val penaltyChargesPortion: Double = 0.0,
    val overpaymentPortion: Double = 0.0,
    val unrecognizedIncomePortion: Double = 0.0,
    val outstandingLoanBalance: Double = 0.0,
    val submittedOnDate: List<Int>? = null,
    val manuallyReversed: Boolean = false,
)

@Serializable
data class LoanTransactionTypeDto(
    val id: Long = 0,
    val code: String? = null,
    val value: String? = null,
    val disbursement: Boolean = false,
    val repaymentAtDisbursement: Boolean = false,
    val repayment: Boolean = false,
    val merchantIssuedRefund: Boolean = false,
    val payoutRefund: Boolean = false,
    val goodwillCredit: Boolean = false,
    val interestPaymentWaiver: Boolean = false,
    val chargeRefund: Boolean = false,
    val contra: Boolean = false,
    val waiveInterest: Boolean = false,
    val waiveCharges: Boolean = false,
    val accrual: Boolean = false,
    val writeOff: Boolean = false,
    val recoveryRepayment: Boolean = false,
    val initiateTransfer: Boolean = false,
    val approveTransfer: Boolean = false,
    val withdrawTransfer: Boolean = false,
    val rejectTransfer: Boolean = false,
    val chargePayment: Boolean = false,
    val refund: Boolean = false,
    val refundForActiveLoans: Boolean = false,
    val creditBalanceRefund: Boolean = false,
    val chargeAdjustment: Boolean = false,
    val chargeback: Boolean = false,
    val chargeoff: Boolean = false,
    val downPayment: Boolean = false,
    val reAge: Boolean = false,
    val reAmortize: Boolean = false,
    val accrualActivity: Boolean = false,
    val interestRefund: Boolean = false,
    val accrualAdjustment: Boolean = false,
    val capitalizedIncome: Boolean = false,
    val capitalizedIncomeAmortization: Boolean = false,
    val capitalizedIncomeAdjustment: Boolean = false,
    val capitalizedIncomeAmortizationAdjustment: Boolean = false,
    val contractTermination: Boolean = false,
    val buyDownFee: Boolean = false,
    val buyDownFeeAdjustment: Boolean = false,
    val buyDownFeeAmortization: Boolean = false,
    val buyDownFeeAmortizationAdjustment: Boolean = false,
)
