/*
 * Copyright 2026 Mifos Initiative
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See See https://github.com/openMF/kmp-project-template/blob/main/LICENSE
 */
package org.mifos.core.model.loans

import kotlinx.datetime.LocalDate

data class LoanDetail(
    val id: Long,
    val accountNo: String?,
    val status: LoanDetailStatus?,
    val clientId: Long,
    val clientAccountNo: String?,
    val clientName: String?,
    val clientOfficeId: Long,
    val loanProductId: Long,
    val loanProductName: String?,
    val loanProductDescription: String?,
    val isLoanProductLinkedToFloatingRate: Boolean,
    val loanType: LoanDetailType?,
    val currency: LoanDetailCurrency?,
    val principal: Double,
    val approvedPrincipal: Double,
    val proposedPrincipal: Double,
    val netDisbursalAmount: Double,
    val termFrequency: Int,
    val termPeriodFrequencyType: LoanDetailType?,
    val numberOfRepayments: Int,
    val actualNoTerm: Int,
    val repaymentEvery: Int,
    val repaymentFrequencyType: LoanDetailType?,
    val interestRatePerPeriod: Double,
    val interestRateFrequencyType: LoanDetailType?,
    val annualInterestRate: Double,
    val isFloatingInterestRate: Boolean,
    val amortizationType: LoanDetailType?,
    val interestType: LoanDetailType?,
    val interestCalculationPeriodType: LoanDetailType?,
    val allowPartialPeriodInterestCalculation: Boolean,
    val transactionProcessingStrategyCode: String?,
    val transactionProcessingStrategyName: String?,
    val syncDisbursementWithMeeting: Boolean,
    val disallowExpectedDisbursements: Boolean,
    val timeline: LoanDetailTimeline?,
    val summary: LoanDetailSummary?,
    val repaymentSchedule: LoanRepaymentSchedule?,
    val transactions: List<LoanTransaction>,
)

data class LoanDetailStatus(
    val id: Long,
    val code: String?,
    val value: String?,
    val pendingApproval: Boolean,
    val waitingForDisbursal: Boolean,
    val active: Boolean,
    val closedObligationsMet: Boolean,
    val closedWrittenOff: Boolean,
    val closedRescheduled: Boolean,
    val closed: Boolean,
    val overpaid: Boolean,
)

data class LoanDetailType(
    val id: Long,
    val code: String?,
    val value: String?,
)

data class LoanDetailCurrency(
    val code: String?,
    val name: String?,
    val decimalPlaces: Int,
    val inMultiplesOf: Int,
    val displaySymbol: String?,
    val nameCode: String?,
    val displayLabel: String?,
)

data class LoanDetailTimeline(
    val submittedOnDate: LocalDate?,
    val submittedByUsername: String?,
    val submittedByFirstname: String?,
    val submittedByLastname: String?,
    val approvedOnDate: LocalDate?,
    val approvedByUsername: String?,
    val approvedByFirstname: String?,
    val approvedByLastname: String?,
    val expectedDisbursementDate: LocalDate?,
    val actualDisbursementDate: LocalDate?,
    val disbursedByUsername: String?,
    val disbursedByFirstname: String?,
    val disbursedByLastname: String?,
    val actualMaturityDate: LocalDate?,
    val expectedMaturityDate: LocalDate?,
)

data class LoanDetailSummary(
    val currency: LoanDetailCurrency?,
    val totalPrincipal: Double,
    val totalCapitalizedIncome: Double,
    val totalCapitalizedIncomeAdjustment: Double,
    val principalDisbursed: Double,
    val principalAdjustments: Double,
    val principalPaid: Double,
    val principalWrittenOff: Double,
    val principalOutstanding: Double,
    val principalOverdue: Double,
    val interestCharged: Double,
    val interestPaid: Double,
    val interestWaived: Double,
    val interestWrittenOff: Double,
    val interestOutstanding: Double,
    val interestOverdue: Double,
    val feeChargesCharged: Double,
    val feeAdjustments: Double,
    val feeChargesDueAtDisbursementCharged: Double,
    val feeChargesPaid: Double,
    val feeChargesWaived: Double,
    val feeChargesWrittenOff: Double,
    val feeChargesOutstanding: Double,
    val feeChargesOverdue: Double,
    val penaltyChargesCharged: Double,
    val penaltyAdjustments: Double,
    val penaltyChargesPaid: Double,
    val penaltyChargesWaived: Double,
    val penaltyChargesWrittenOff: Double,
    val penaltyChargesOutstanding: Double,
    val penaltyChargesOverdue: Double,
    val totalExpectedRepayment: Double,
    val totalRepayment: Double,
    val totalExpectedCostOfLoan: Double,
    val totalCostOfLoan: Double,
    val totalWaived: Double,
    val totalWrittenOff: Double,
    val totalOutstanding: Double,
    val totalOverdue: Double,
    val totalRecovered: Double,
)

data class LoanRepaymentSchedule(
    val currency: LoanDetailCurrency?,
    val loanTermInDays: Int,
    val totalPrincipalDisbursed: Double,
    val totalPrincipalExpected: Double,
    val totalPrincipalPaid: Double,
    val totalInterestCharged: Double,
    val totalFeeChargesCharged: Double,
    val totalPenaltyChargesCharged: Double,
    val totalWaived: Double,
    val totalWrittenOff: Double,
    val totalRepaymentExpected: Double,
    val totalRepayment: Double,
    val totalPaidInAdvance: Double,
    val totalPaidLate: Double,
    val totalOutstanding: Double,
    val totalCredits: Double,
    val periods: List<LoanRepaymentPeriod>,
)

data class LoanRepaymentPeriod(
    val period: Int?,
    val fromDate: LocalDate?,
    val dueDate: LocalDate?,
    val complete: Boolean,
    val daysInPeriod: Int?,
    val principalOriginalDue: Double,
    val principalDue: Double,
    val principalPaid: Double,
    val principalWrittenOff: Double,
    val principalOutstanding: Double,
    val principalLoanBalanceOutstanding: Double,
    val interestOriginalDue: Double,
    val interestDue: Double,
    val interestPaid: Double,
    val interestWaived: Double,
    val interestWrittenOff: Double,
    val interestOutstanding: Double,
    val feeChargesDue: Double,
    val feeChargesPaid: Double,
    val feeChargesWaived: Double,
    val feeChargesWrittenOff: Double,
    val feeChargesOutstanding: Double,
    val penaltyChargesDue: Double,
    val penaltyChargesPaid: Double,
    val penaltyChargesWaived: Double,
    val penaltyChargesWrittenOff: Double,
    val penaltyChargesOutstanding: Double,
    val totalOriginalDueForPeriod: Double,
    val totalDueForPeriod: Double,
    val totalPaidForPeriod: Double,
    val totalPaidInAdvanceForPeriod: Double,
    val totalPaidLateForPeriod: Double,
    val totalWaivedForPeriod: Double,
    val totalWrittenOffForPeriod: Double,
    val totalOutstandingForPeriod: Double,
    val totalActualCostOfLoanForPeriod: Double,
    val totalInstallmentAmountForPeriod: Double,
    val totalCredits: Double,
    val totalAccruedInterest: Double,
    val downPaymentPeriod: Boolean,
)

data class LoanTransaction(
    val id: Long,
    val loanId: Long,
    val officeId: Long,
    val officeName: String?,
    val type: LoanTransactionType?,
    val date: LocalDate?,
    val currency: LoanDetailCurrency?,
    val amount: Double,
    val netDisbursalAmount: Double,
    val principalPortion: Double,
    val interestPortion: Double,
    val feeChargesPortion: Double,
    val penaltyChargesPortion: Double,
    val overpaymentPortion: Double,
    val unrecognizedIncomePortion: Double,
    val outstandingLoanBalance: Double,
    val submittedOnDate: LocalDate?,
    val manuallyReversed: Boolean,
)

data class LoanTransactionType(
    val id: Long,
    val code: String?,
    val value: String?,
    val disbursement: Boolean,
    val repaymentAtDisbursement: Boolean,
    val repayment: Boolean,
    val merchantIssuedRefund: Boolean,
    val payoutRefund: Boolean,
    val goodwillCredit: Boolean,
    val interestPaymentWaiver: Boolean,
    val chargeRefund: Boolean,
    val contra: Boolean,
    val waiveInterest: Boolean,
    val waiveCharges: Boolean,
    val accrual: Boolean,
    val writeOff: Boolean,
    val recoveryRepayment: Boolean,
    val initiateTransfer: Boolean,
    val approveTransfer: Boolean,
    val withdrawTransfer: Boolean,
    val rejectTransfer: Boolean,
    val chargePayment: Boolean,
    val refund: Boolean,
    val refundForActiveLoans: Boolean,
    val creditBalanceRefund: Boolean,
    val chargeAdjustment: Boolean,
    val chargeback: Boolean,
    val chargeoff: Boolean,
    val downPayment: Boolean,
    val reAge: Boolean,
    val reAmortize: Boolean,
    val accrualActivity: Boolean,
    val interestRefund: Boolean,
    val accrualAdjustment: Boolean,
    val capitalizedIncome: Boolean,
    val capitalizedIncomeAmortization: Boolean,
    val capitalizedIncomeAdjustment: Boolean,
    val capitalizedIncomeAmortizationAdjustment: Boolean,
    val contractTermination: Boolean,
    val buyDownFee: Boolean,
    val buyDownFeeAdjustment: Boolean,
    val buyDownFeeAmortization: Boolean,
    val buyDownFeeAmortizationAdjustment: Boolean,
)
